// Flag emojis are just two "regional indicator" letters, so every flag can be
// derived from its ISO country code instead of pasting hundreds of characters.
export const flagOf = (code) =>
  String.fromCodePoint(...[...code.toUpperCase()].map((c) => 127397 + c.charCodeAt(0)));

// Study-abroad destinations first, then the rest of the commonly asked-about
// countries. `search` carries extra words students actually type.
const COUNTRIES = [
  ['US', 'United States', 'usa america'],
  ['GB', 'United Kingdom', 'uk britain england'],
  ['CA', 'Canada', ''],
  ['AU', 'Australia', ''],
  ['DE', 'Germany', 'deutschland'],
  ['IE', 'Ireland', ''],
  ['NZ', 'New Zealand', ''],
  ['AE', 'United Arab Emirates', 'uae dubai abu dhabi'],
  ['SG', 'Singapore', ''],
  ['FR', 'France', ''],
  ['NL', 'Netherlands', 'holland dutch'],
  ['IT', 'Italy', ''],
  ['ES', 'Spain', ''],
  ['SE', 'Sweden', ''],
  ['NO', 'Norway', ''],
  ['DK', 'Denmark', ''],
  ['FI', 'Finland', ''],
  ['CH', 'Switzerland', ''],
  ['AT', 'Austria', ''],
  ['BE', 'Belgium', ''],
  ['PL', 'Poland', ''],
  ['CZ', 'Czechia', 'czech republic prague'],
  ['PT', 'Portugal', ''],
  ['GR', 'Greece', ''],
  ['HU', 'Hungary', ''],
  ['LT', 'Lithuania', ''],
  ['LV', 'Latvia', ''],
  ['EE', 'Estonia', ''],
  ['MT', 'Malta', ''],
  ['CY', 'Cyprus', ''],
  ['IN', 'India', ''],
  ['CN', 'China', ''],
  ['JP', 'Japan', ''],
  ['KR', 'South Korea', 'korea'],
  ['MY', 'Malaysia', ''],
  ['TH', 'Thailand', ''],
  ['PH', 'Philippines', ''],
  ['ID', 'Indonesia', ''],
  ['VN', 'Vietnam', ''],
  ['HK', 'Hong Kong', ''],
  ['TW', 'Taiwan', ''],
  ['QA', 'Qatar', ''],
  ['SA', 'Saudi Arabia', ''],
  ['OM', 'Oman', ''],
  ['BH', 'Bahrain', ''],
  ['KW', 'Kuwait', ''],
  ['TR', 'Turkey', 'turkiye'],
  ['RU', 'Russia', ''],
  ['UA', 'Ukraine', ''],
  ['GE', 'Georgia', ''],
  ['AM', 'Armenia', ''],
  ['KZ', 'Kazakhstan', ''],
  ['UZ', 'Uzbekistan', ''],
  ['ZA', 'South Africa', ''],
  ['EG', 'Egypt', ''],
  ['KE', 'Kenya', ''],
  ['NG', 'Nigeria', ''],
  ['GH', 'Ghana', ''],
  ['MU', 'Mauritius', ''],
  ['BR', 'Brazil', ''],
  ['AR', 'Argentina', ''],
  ['MX', 'Mexico', ''],
  ['CL', 'Chile', ''],
  ['NP', 'Nepal', ''],
  ['LK', 'Sri Lanka', ''],
  ['BD', 'Bangladesh', ''],
  ['PK', 'Pakistan', ''],
  ['BT', 'Bhutan', ''],
  ['MV', 'Maldives', ''],
];

export const FLAG_EMOJIS = COUNTRIES.map(([code, name, search]) => ({
  char: flagOf(code),
  label: name,
  search: `${name} ${code} ${search}`.toLowerCase(),
}));

// Subject icons for course cards.
const SYMBOLS = [
  ['📊', 'data analytics chart statistics'],
  ['📈', 'business growth management mba finance'],
  ['💻', 'computer science software it coding'],
  ['🤖', 'ai artificial intelligence robotics machine learning'],
  ['🧠', 'psychology neuroscience cognitive'],
  ['🔬', 'science research laboratory'],
  ['🧬', 'biotech biology genetics life sciences'],
  ['🩺', 'medicine nursing health doctor clinical'],
  ['💊', 'pharmacy pharmaceutical drugs'],
  ['🦷', 'dentistry dental'],
  ['⚙️', 'mechanical engineering manufacturing'],
  ['🏗️', 'civil engineering construction architecture'],
  ['⚡', 'electrical engineering energy power'],
  ['🚗', 'automotive vehicles transport'],
  ['✈️', 'aerospace aviation aeronautical'],
  ['🛰️', 'space satellite astronomy'],
  ['💰', 'finance banking accounting economics money'],
  ['📉', 'economics markets trading'],
  ['⚖️', 'law legal llm justice'],
  ['🌍', 'international relations politics global studies'],
  ['🏛️', 'public policy government history'],
  ['🎨', 'design ux graphic art'],
  ['🎬', 'film animation vfx media production'],
  ['📸', 'photography visual media'],
  ['🎵', 'music audio sound'],
  ['📚', 'literature education teaching humanities'],
  ['🗣️', 'languages linguistics communication'],
  ['📰', 'journalism media communications'],
  ['🏨', 'hospitality hotel tourism'],
  ['🍳', 'culinary cooking chef food'],
  ['🌱', 'agriculture environment sustainability'],
  ['🐾', 'veterinary animal science'],
  ['⛏️', 'mining geology earth sciences'],
  ['🏅', 'sports science physical education'],
  ['🎓', 'general education degree study'],
  ['🧾', 'actuarial insurance risk'],
  ['🔐', 'cybersecurity security information'],
  ['📐', 'mathematics statistics'],
  ['🧱', 'materials science'],
  ['🚢', 'marine maritime logistics shipping'],
];

export const SYMBOL_EMOJIS = SYMBOLS.map(([char, search]) => ({
  char,
  label: search.split(' ')[0],
  search,
}));

export const EMOJI_SETS = { flags: FLAG_EMOJIS, symbols: SYMBOL_EMOJIS };
